# To run
#    docker-compose up --build

version: '3'
services:
  vue-ui:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:80"    # Container port 80 is mapped to port 9000 on the host
    # volumes:
      # - .:/usr/src/app/spherical
      # - /usr/src/app/spherical/node_modules

  session-server:
    build:
      context: .
      dockerfile: Dockerfile-exp
    ports:
      - "4000:4000"
